use crate::gpio::{BankId, BankInfo, Capabilities, PinInfo, PinMap};

pub const BANK_A: BankId = BankId::new(0);
pub const BANK_B: BankId = BankId::new(1);
pub const BANK_C: BankId = BankId::new(2);
pub const BANK_D: BankId = BankId::new(3);
pub const BANK_E: BankId = BankId::new(4);

pub const SAM_IDENTITY: &[u8] = b"SAM4E8E GPIO";

static BANKS: [BankInfo; 5] = [
    BankInfo::new("PIOA"),
    BankInfo::new("PIOB"),
    BankInfo::new("PIOC"),
    BankInfo::new("PIOD"),
    BankInfo::new("PIOE"),
];

static PINS: [PinInfo; 117] = [
    PinInfo::new("PA00", Some(102), BANK_A, 0, Capabilities::GPIO),
    PinInfo::new("PA01", Some(99), BANK_A, 1, Capabilities::GPIO),
    PinInfo::new("PA02", Some(93), BANK_A, 2, Capabilities::GPIO),
    PinInfo::new("PA03", Some(91), BANK_A, 3, Capabilities::GPIO),
    PinInfo::new("PA04", Some(77), BANK_A, 4, Capabilities::GPIO),
    PinInfo::new("PA05", Some(73), BANK_A, 5, Capabilities::GPIO),
    PinInfo::new("PA06", Some(114), BANK_A, 6, Capabilities::GPIO),
    PinInfo::new("PA07", Some(35), BANK_A, 7, Capabilities::GPIO),
    PinInfo::new("PA08", Some(36), BANK_A, 8, Capabilities::GPIO),
    PinInfo::new("PA09", Some(75), BANK_A, 9, Capabilities::GPIO),
    PinInfo::new("PA10", Some(66), BANK_A, 10, Capabilities::GPIO),
    PinInfo::new("PA11", Some(64), BANK_A, 11, Capabilities::GPIO),
    PinInfo::new("PA12", Some(68), BANK_A, 12, Capabilities::GPIO),
    PinInfo::new("PA13", Some(42), BANK_A, 13, Capabilities::GPIO),
    PinInfo::new("PA14", Some(51), BANK_A, 14, Capabilities::GPIO),
    PinInfo::new("PA15", Some(49), BANK_A, 15, Capabilities::GPIO),
    PinInfo::new("PA16", Some(45), BANK_A, 16, Capabilities::GPIO),
    PinInfo::new("PA17", Some(25), BANK_A, 17, Capabilities::GPIO),
    PinInfo::new("PA18", Some(24), BANK_A, 18, Capabilities::GPIO),
    PinInfo::new("PA19", Some(23), BANK_A, 19, Capabilities::GPIO),
    PinInfo::new("PA20", Some(22), BANK_A, 20, Capabilities::GPIO),
    PinInfo::new("PA21", Some(32), BANK_A, 21, Capabilities::GPIO),
    PinInfo::new("PA22", Some(37), BANK_A, 22, Capabilities::GPIO),
    PinInfo::new("PA23", Some(46), BANK_A, 23, Capabilities::GPIO),
    PinInfo::new("PA24", Some(56), BANK_A, 24, Capabilities::GPIO),
    PinInfo::new("PA25", Some(59), BANK_A, 25, Capabilities::GPIO),
    PinInfo::new("PA26", Some(62), BANK_A, 26, Capabilities::GPIO),
    PinInfo::new("PA27", Some(70), BANK_A, 27, Capabilities::GPIO),
    PinInfo::new("PA28", Some(112), BANK_A, 28, Capabilities::GPIO),
    PinInfo::new("PA29", Some(129), BANK_A, 29, Capabilities::GPIO),
    PinInfo::new("PA30", Some(116), BANK_A, 30, Capabilities::GPIO),
    PinInfo::new("PA31", Some(118), BANK_A, 31, Capabilities::GPIO),
    PinInfo::new("PB00", Some(21), BANK_B, 0, Capabilities::GPIO),
    PinInfo::new("PB01", Some(20), BANK_B, 1, Capabilities::GPIO),
    PinInfo::new("PB02", Some(26), BANK_B, 2, Capabilities::GPIO),
    PinInfo::new("PB03", Some(31), BANK_B, 3, Capabilities::GPIO),
    PinInfo::new("PB04", Some(105), BANK_B, 4, Capabilities::GPIO),
    PinInfo::new("PB05", Some(109), BANK_B, 5, Capabilities::GPIO),
    PinInfo::new("PB06", Some(79), BANK_B, 6, Capabilities::GPIO),
    PinInfo::new("PB07", Some(89), BANK_B, 7, Capabilities::GPIO),
    PinInfo::new("PB08", Some(141), BANK_B, 8, Capabilities::NONE),
    PinInfo::new("PB09", Some(142), BANK_B, 9, Capabilities::NONE),
    PinInfo::new("PB10", Some(136), BANK_B, 10, Capabilities::NONE),
    PinInfo::new("PB11", Some(137), BANK_B, 11, Capabilities::NONE),
    PinInfo::new("PB12", Some(87), BANK_B, 12, Capabilities::GPIO),
    PinInfo::new("PB13", Some(144), BANK_B, 13, Capabilities::GPIO),
    PinInfo::new("PB14", Some(140), BANK_B, 14, Capabilities::GPIO),
    PinInfo::new("PC00", Some(11), BANK_C, 0, Capabilities::GPIO),
    PinInfo::new("PC01", Some(38), BANK_C, 1, Capabilities::GPIO),
    PinInfo::new("PC02", Some(39), BANK_C, 2, Capabilities::GPIO),
    PinInfo::new("PC03", Some(40), BANK_C, 3, Capabilities::GPIO),
    PinInfo::new("PC04", Some(41), BANK_C, 4, Capabilities::GPIO),
    PinInfo::new("PC05", Some(58), BANK_C, 5, Capabilities::GPIO),
    PinInfo::new("PC06", Some(54), BANK_C, 6, Capabilities::GPIO),
    PinInfo::new("PC07", Some(48), BANK_C, 7, Capabilities::GPIO),
    PinInfo::new("PC08", Some(82), BANK_C, 8, Capabilities::GPIO),
    PinInfo::new("PC09", Some(86), BANK_C, 9, Capabilities::GPIO),
    PinInfo::new("PC10", Some(90), BANK_C, 10, Capabilities::GPIO),
    PinInfo::new("PC11", Some(94), BANK_C, 11, Capabilities::GPIO),
    PinInfo::new("PC12", Some(17), BANK_C, 12, Capabilities::GPIO),
    PinInfo::new("PC13", Some(19), BANK_C, 13, Capabilities::GPIO),
    PinInfo::new("PC14", Some(97), BANK_C, 14, Capabilities::GPIO),
    PinInfo::new("PC15", Some(18), BANK_C, 15, Capabilities::GPIO),
    PinInfo::new("PC16", Some(100), BANK_C, 16, Capabilities::GPIO),
    PinInfo::new("PC17", Some(103), BANK_C, 17, Capabilities::GPIO),
    PinInfo::new("PC18", Some(111), BANK_C, 18, Capabilities::GPIO),
    PinInfo::new("PC19", Some(117), BANK_C, 19, Capabilities::GPIO),
    PinInfo::new("PC20", Some(120), BANK_C, 20, Capabilities::GPIO),
    PinInfo::new("PC21", Some(122), BANK_C, 21, Capabilities::GPIO),
    PinInfo::new("PC22", Some(124), BANK_C, 22, Capabilities::GPIO),
    PinInfo::new("PC23", Some(127), BANK_C, 23, Capabilities::GPIO),
    PinInfo::new("PC24", Some(130), BANK_C, 24, Capabilities::GPIO),
    PinInfo::new("PC25", Some(133), BANK_C, 25, Capabilities::GPIO),
    PinInfo::new("PC26", Some(13), BANK_C, 26, Capabilities::GPIO),
    PinInfo::new("PC27", Some(12), BANK_C, 27, Capabilities::GPIO),
    PinInfo::new("PC28", Some(76), BANK_C, 28, Capabilities::GPIO),
    PinInfo::new("PC29", Some(16), BANK_C, 29, Capabilities::GPIO),
    PinInfo::new("PC30", Some(15), BANK_C, 30, Capabilities::GPIO),
    PinInfo::new("PC31", Some(14), BANK_C, 31, Capabilities::GPIO),
    PinInfo::new("PD00", Some(1), BANK_D, 0, Capabilities::GPIO),
    PinInfo::new("PD01", Some(132), BANK_D, 1, Capabilities::GPIO),
    PinInfo::new("PD02", Some(131), BANK_D, 2, Capabilities::GPIO),
    PinInfo::new("PD03", Some(128), BANK_D, 3, Capabilities::GPIO),
    PinInfo::new("PD04", Some(126), BANK_D, 4, Capabilities::GPIO),
    PinInfo::new("PD05", Some(125), BANK_D, 5, Capabilities::GPIO),
    PinInfo::new("PD06", Some(121), BANK_D, 6, Capabilities::GPIO),
    PinInfo::new("PD07", Some(119), BANK_D, 7, Capabilities::GPIO),
    PinInfo::new("PD08", Some(113), BANK_D, 8, Capabilities::GPIO),
    PinInfo::new("PD09", Some(110), BANK_D, 9, Capabilities::GPIO),
    PinInfo::new("PD10", Some(101), BANK_D, 10, Capabilities::GPIO),
    PinInfo::new("PD11", Some(98), BANK_D, 11, Capabilities::GPIO),
    PinInfo::new("PD12", Some(92), BANK_D, 12, Capabilities::GPIO),
    PinInfo::new("PD13", Some(88), BANK_D, 13, Capabilities::GPIO),
    PinInfo::new("PD14", Some(84), BANK_D, 14, Capabilities::GPIO),
    PinInfo::new("PD15", Some(106), BANK_D, 15, Capabilities::GPIO),
    PinInfo::new("PD16", Some(78), BANK_D, 16, Capabilities::GPIO),
    PinInfo::new("PD17", Some(74), BANK_D, 17, Capabilities::GPIO),
    PinInfo::new("PD18", Some(69), BANK_D, 18, Capabilities::GPIO),
    PinInfo::new("PD19", Some(67), BANK_D, 19, Capabilities::GPIO),
    PinInfo::new("PD20", Some(65), BANK_D, 20, Capabilities::GPIO),
    PinInfo::new("PD21", Some(63), BANK_D, 21, Capabilities::GPIO),
    PinInfo::new("PD22", Some(60), BANK_D, 22, Capabilities::GPIO),
    PinInfo::new("PD23", Some(57), BANK_D, 23, Capabilities::GPIO),
    PinInfo::new("PD24", Some(55), BANK_D, 24, Capabilities::GPIO),
    PinInfo::new("PD25", Some(52), BANK_D, 25, Capabilities::GPIO),
    PinInfo::new("PD26", Some(53), BANK_D, 26, Capabilities::GPIO),
    PinInfo::new("PD27", Some(47), BANK_D, 27, Capabilities::GPIO),
    PinInfo::new("PD28", Some(71), BANK_D, 28, Capabilities::GPIO),
    PinInfo::new("PD29", Some(108), BANK_D, 29, Capabilities::GPIO),
    PinInfo::new("PD30", Some(34), BANK_D, 30, Capabilities::GPIO),
    PinInfo::new("PD31", Some(2), BANK_D, 31, Capabilities::GPIO),
    PinInfo::new("PE00", Some(4), BANK_E, 0, Capabilities::GPIO),
    PinInfo::new("PE01", Some(6), BANK_E, 1, Capabilities::GPIO),
    PinInfo::new("PE02", Some(7), BANK_E, 2, Capabilities::GPIO),
    PinInfo::new("PE03", Some(10), BANK_E, 3, Capabilities::GPIO),
    PinInfo::new("PE04", Some(27), BANK_E, 4, Capabilities::GPIO),
    PinInfo::new("PE05", Some(28), BANK_E, 5, Capabilities::GPIO),
];

pub static SAM_PIN_MAP: PinMap = PinMap::new(&BANKS, &PINS);
